// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Provides Firebase configuration for the NIT Goa Gate System project
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return windows;
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqlf7wqLSe_example', // Replace with your API key
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '123456789',
    appId: '1:123456789:web:abcdef1234567890',
    // Leave these empty for desktop only - they're for web/mobile
    authDomain: '',
    databaseURL: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlf7wqLSe_example', // Replace with Android key
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '123456789',
    appId: '1:123456789:android:abcdef1234567890',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlf7wqLSe_example', // Replace with iOS key
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '123456789',
    appId: '1:123456789:ios:abcdef1234567890',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlf7wqLSe_example', // Replace with macOS key
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '123456789',
    appId: '1:123456789:macos:abcdef1234567890',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlf7wqLSe_example', // Replace with Web key
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '123456789',
    appId: '1:123456789:web:abcdef1234567890',
    authDomain: 'nit-goa-gate-system.firebaseapp.com',
    databaseURL: 'https://nit-goa-gate-system.firebasedatabase.app',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );
}
